export const ACTIONS = {  
  CREATE_FILE: 'ADD_NEW_FILE',
  OPEN_FILE: 'OPEN_FILE',
  RENAME_FILE: 'RENAME_FILE',
  DELETE_FILE: 'DELETE_FILE',
  COPY_FILE: 'COPY_FILE',
  CUT_FILE: 'CUT_FILE',
  SET_INDEX_CURRENT_FILE: 'SET_CURRENT_FILE',
  CLOSE_FILE: 'CLOSE_FILE',
  UPDATE_FILE: 'UPDATE_FILE',
  SET_FILE_MODIFIED: 'SET_FILE_MODIFIED'
};

